### ISSUE TITLE
Not able to load

### ISSUE THREAD

**Issue by GaviTSRA** [Xpdustry/ModLoaderPlugin#1]
Mindustry v126.2

Error:
[06-28-2022 16:45:51] [E] java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at mindustry.mod.Mods.loadMod(Mods.java:707)
        at mindustry.mod.Mods.loadMod(Mods.java:620)
        at mindustry.mod.Mods.load(Mods.java:275)
        at mindustry.Vars.init(Vars.java:287)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:57)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:66)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: java.lang.NoSuchMethodError: 'void arc.util.Log.debug(java.lang.Object)'
        at fr.xpdustry.loader.ModLoaderPlugin.resolveDependencies(ModLoaderPlugin.java:178)
        at fr.xpdustry.loader.ModLoaderPlugin.<init>(ModLoaderPlugin.java:45)
        ... 12 more

**Comment by phinner** [comment]
That's only now I see this issue ???

**Comment by phinner** [comment]
Ok @GaviTSRA, I have no idea how this issue could ever occur.
I mean, if `Log.debug` is available at compile time, it should be available at runtime.
But the stacktrace tell it's not the case:
```java
Caused by: java.lang.NoSuchMethodError: 'void arc.util.Log.debug(java.lang.Object)'
at fr.xpdustry.loader.ModLoaderPlugin.resolveDependencies(ModLoaderPlugin.java:178)
at fr.xpdustry.loader.ModLoaderPlugin.(ModLoaderPlugin.java:45)
... 12 more
```

This is quite confusing, I will close it for now, if you still need help, feel free to contact me on [discord](https://discord.xpdustry.fr).
